use_default_settings: true

server:
  secret_key: "b0b17906390d3ac58b9336a0cfbf43bee0d04462b7be6d3918fe2a78198ab974"
  limiter: false

search:
  safe_search: 0
  autocomplete: "google"

  formats:
    - html
    - json

outgoing:
  requests_timeout: 5.0
  max_request_timeout: 10.0

  
engines:
  - name: google
    engine: google
    shortcut: g
    disabled: true

  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    disabled: true

  - name: brave
    engine: brave
    shortcut: b
    disabled: true

  - name: bing
    engine: bing
    shortcut: bi
    disabled: false

  - name: wikipedia
    engine: wikipedia
    shortcut: wp
    disabled: false

  - name: arxiv
    engine: arxiv
    shortcut: ax
    timeout: 10.0
    disabled: false

  - name: semantic_scholar
    engine: semantic_scholar
    shortcut: ss
    disabled: true
  
  - name: pubmed
    engine: pubmed
    shortcut: pm
    disabled: false

  - name: crossref
    engine: crossref
    shortcut: cr
    disabled: false

  - name: github
    engine: github
    shortcut: gh
    disabled: false
  
  - name: stackoverflow
    engine: stackexchange
    shortcut: so
    disabled: false

hostnames:
  remove:
    - '(.*\.)?merriam-webster\.com$'
    - '(.*\.)?dictionary\.cambridge\.org$'
    - '(.*\.)?dictionary\.com$'
    - '(.*\.)?collinsdictionary\.com$'
    - '(.*\.)?thesaurus\.com$'
    - '(.*\.)?pinterest\.com$'
    - '(.*\.)?facebook\.com$'
    - '(.*\.)?instagram\.com$'
    - '(.*\.)?tiktok\.com$'
    - '(.*\.)?x\.com$'
    - '(.*\.)?twitter\.com$'
    - '(.*\.)?linkedin\.com$'

  